# This is a basic workflow to help you get started with Actions

name: Python CI

# Controls when the action will run. 
on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Bazel version

        uses: ngalaiko/bazel-action@2.0.0
        with:
          # Arguments to the bazel command
          args: version

      - name: Bazel sync

        uses: ngalaiko/bazel-action@2.0.0
        with:
          args: sync
      
      - name: Bazel test

        uses: ngalaiko/bazel-action@2.0.0
        with:
          args: test --test_output=all //...
